language: go
go:       "1.10"

services:
  - docker

env:
  global:
    - PATH=$HOME/.wantedly/bin:$PATH

cache:
  directories:
    - vendor

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get -u github.com/golang/lint/golint

install:
  - dep ensure -v
  - bash <(curl -sL https://get.wantedlyapp.com/kube)

script:
  - go vet -v
  - go test -v
  - kube ci-build
